# Generated by Django 4.2.14 on 2024-07-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0444_integration_unique_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertCheck",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("calculated_value", models.FloatField(null=True)),
                ("anomaly_condition", models.JSONField(default=dict)),
                (
                    "check_result",
                    models.CharField(
                        choices=[("NORMAL_VALUE", "Normalvalue"), ("ANOMALY", "Anomaly"), ("ERROR", "Error")],
                        max_length=20,
                    ),
                ),
                ("error_message", models.CharField(null=True)),
                ("alert", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="posthog.alert")),
            ],
        ),
    ]
